run:
  deadline: 15m
  issues-exit-code: 1
  modules-download-mode: readonly
issues:
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - deadcode
    - gas
    - goconst
    - gofmt
    - govet
    - ineffassign
    - lll
    - megacheck
    - misspell
    - structcheck
    - staticcheck
    - unconvert
    - varcheck
